Repository EmeraldLabs/chatpdf-gpt, pull requests merged in 2023-10, with the labels that each got.

#1 Pulling Credentials from ENV in Chat API
  app/api/chat/route.ts
Labels: enhancement

#2 Chat Enhancements
  app/api/chat/init/route.ts
  app/api/chat/route.ts
  prisma/migrations/20231002122742_added_chat_history_table/migration.sql
  prisma/migrations/20231002132845_added_title_column_in_chathistory_table/migration.sql
  prisma/migrations/20231002133243_updated_chathistory_table/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  utils/chat.ts
Labels: enhancement

#3 Enhancement/Chat Feature
  app/api/chat-listing/[childId]/route.ts
  app/api/chat/[id]/route.ts
Labels: enhancement

#4 Temporary Chat title is added on chat initialization
  app/api/chat/init/route.ts
Labels: enhancement

#5 Fixing Namespace issue
  app/api/documents/route.ts
  lib/langchain/vectorstores/pinecone.ts
Labels: bug

#6 Ns/allow multiple fileuploads
  app/api/documents/route.ts
  app/page.tsx
Labels: enhancement

#8 Updated At Date is Fixed
  app/api/chat/route.ts
Labels: bug

#9 Production Deployment 1.0.0
  .env.example
  Procfile
  README.md
  app/api/chat-listing/[childId]/route.ts
  app/api/chat/[id]/route.ts
  app/api/chat/init/route.ts
  app/api/chat/route.ts
  app/api/documents/route.ts
  app/credentials/page.tsx
  app/page.tsx
  config/pinecone.ts
  context/credentials-context.tsx
  lib/langchain/vectorstores/pinecone.ts
  package.json
  pnpm-lock.yaml
  prisma/migrations/20231002122742_added_chat_history_table/migration.sql
  prisma/migrations/20231002132845_added_title_column_in_chathistory_table/migration.sql
  prisma/migrations/20231002133243_updated_chathistory_table/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  utils/chat.ts
  utils/pinecone-client.ts
Labels: release

#10 Langchain Method for Chaining is updated
  app/api/chat/route.ts
  lib/langchain/chain.ts
  utils/chat.ts
Labels: bug

#13 Production Deployment 1.0.2
  app/api/chat/route.ts
Labels: release
